spring:
  application:
    name: backend
  profiles:
    active: local # 기본적으로 local 설정을 읽어라!

  # 2. MariaDB 드라이버 (어느 환경이든 드라이버 종류는 같음)
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

  # 4. 파일 업로드 설정 (운영이든 로컬이든 용량 제한은 보통 같게 둠)
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
